### ISSUE TITLE
🤖 Sync error for commit b65cf8

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/go#2060]
We hit an error trying to sync the latest commit (b65cf84250b5aeeb038af3c8c8b07a59a8ed1de0) to the website.

The error was:
```
undefined method `uuid' for #<Hash:0x000055e3522de1b0>

/usr/src/app/app/models/git/track.rb:84:in `block in concepts'
/usr/src/app/app/models/git/track.rb:84:in `select'
/usr/src/app/app/models/git/track.rb:84:in `concepts'
/usr/local/bundle/gems/mandate-1.0.0.beta1/lib/mandate/memoize.rb:47:in `block (2 levels) in __mandate_memoize'
/usr/src/app/app/commands/git/sync_track.rb:71:in `sync_concepts!'
/usr/local/bundle/gems/mandate-1.0.0.beta1/lib/mandate/memoize.rb:47:in `block (2 levels) in __mandate_memoize'
/usr/src/app/app/commands/git/sync_track.rb:37:in `call'
/usr/local/bundle/gems/mandate-1.0.0.beta1/lib/mandate/call_injector.rb:17:in `call'
(irb):9:in `irb_binding'
/usr/local/lib/ruby/2.6.0/irb/workspace.rb:85:in `eval'
/usr/local/lib/ruby/2.6.0/irb/workspace.rb:85:in `evaluate'
/usr/local/lib/ruby/2.6.0/irb/context.rb:385:in `evaluate'
/usr/local/lib/ruby/2.6.0/irb.rb:493:in `block (2 levels) in eval_input'
/usr/local/lib/ruby/2.6.0/irb.rb:647:in `signal_status'
/usr/local/lib/ruby/2.6.0/irb.rb:490:in `block in eval_input'
/usr/local/lib/ruby/2.6.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/usr/local/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `loop'
/usr/local/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/usr/local/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `catch'
/usr/local/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/usr/local/lib/ruby/2.6.0/irb.rb:489:in `eval_input'
/usr/local/lib/ruby/2.6.0/irb.rb:428:in `block in run'
/usr/local/lib/ruby/2.6.0/irb.rb:427:in `catch'
/usr/local/lib/ruby/2.6.0/irb.rb:427:in `run'
/usr/local/lib/ruby/2.6.0/irb.rb:383:in `start'
/usr/local/bundle/gems/railties-6.1.4.1/lib/rails/commands/console/console_command.rb:70:in `start'
/usr/local/bundle/gems/railties-6.1.4.1/lib/rails/commands/console/console_command.rb:19:in `start'
/usr/local/bundle/gems/railties-6.1.4.1/lib/rails/commands/console/console_command.rb:102:in `perform'
/usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/railties-6.1.4.1/lib/rails/command/base.rb:69:in `perform'
/usr/local/bundle/gems/railties-6.1.4.1/lib/rails/command.rb:48:in `invoke'
/usr/local/bundle/gems/railties-6.1.4.1/lib/rails/commands.rb:18:in `<main>'
/usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
bin/rails:4:in `<main>'
```

Please tag @exercism/maintainers-admin if you require more information.

**Comment by andrerfcsantos** [comment]
@exercism/maintainers-admin Is there any action needed from us here?

**Comment by ErikSchierboom** [comment]
There isn't, which is why I closed it. Sorry!
